export const FETCH_LAUNCHDATA_REQUEST = 'FETCH_LAUNCHDATA_REQUEST'
export const FETCH_LAUNCHDATA_SUCCESS = 'FETCH_LAUNCHDATA_SUCCESS'
export const FETCH_LAUNCHDATA_FAILURE = 'FETCH_LAUNCHDATA_FAILURE'
export const FILTER = "FILTER"


