export const FETCH_LAUNCHDATA_REQUEST = 'FETCH_LAUNCHDATA_REQUEST'
export const FETCH_LAUNCHDATA_SUCCESS = 'FETCH_LAUNCHDATA_SUCCESS'
export const FETCH_LAUNCHDATA_FAILURE = 'FETCH_LAUNCHDATA_FAILURE'
export const FILTER_BY_STATUS = "FILTER_BY_STATUS"
export const FILTER_BY_START_DATE= "FILTER_BY_START_DATE"
export const FILTER_BY_END_DATE= "FILTER_BY_END_DATE"


